name: GH Helm Chart Publisher
description: Allows for publishing a helm chart and pushing it to a branch published by GH Pages
author: https://github.com/tylerauerbeck
requirements:
configuration:
  properties:
    token:
      type: string
    charts_dir:
      type: string
    charts_url:
      type: string
    repository_owner:
      type: string
    debug_plugin:
      type: string
    repository:
      type: string
    branch:
      type: string
    target_dir:
      type: string
    helm_version:
      type: string
    helm_linting:
      type: bool
    commit_username:
      type: string
    commit_email:
      type: string
    app_version:
      type: string
    chart_version:
      type: string
    index_dir:
      type: string
    enterprise_url:
      type: string
additionalProperties: false
